### ISSUE TITLE
Recipe app project

### ISSUE THREAD

**Issue by Alejandroq12** [Alejandroq12/recipe-app#11]
Hello, dear reviewer.

We are two team members @Nessrine88 and me @Alejandroq12.

This is our project link: 
https://github.com/users/Alejandroq12/projects/4/views/1

Thank you very much for your time.

**Comment by Whoistolu** [comment]
### Hi @Alejandroq12 and @Nessrine88 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
